---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # 
pip_package: python3-pip                               # geerlingguy.pip

# PostgreSQL
postgresql_objects_users:
  - name: galaxy
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy
postgresql_pg_hba_local_socket : true    

# PostgreSQL Backups
postgresql_backup_dir: /storage/galaxy/backups
postgresql_backup_local_dir: "~postgres/backups"

# Nginx
### variables that are used in the galaxy.conf templates
### if no ssl, leave the ssl_cert_path and ssl_key_path empty
use_ssl: true
ssl_cert_path: /etc/pki/tls/certs/galaxy01_educloud_no.crt;
ssl_key_path: /etc/pki/tls/private/galaxy01.educloud.no.key;

# Galaxy

# only for RHEL8 otherwise "true"
galaxy_create_user: false
galaxy_separate_privileges: true
galaxy_manage_paths: true
galaxy_root: /srv/galaxy
galaxy_layout: root-dir
#----------------------------------------------------------------------
galaxy_user: {name: ec-galaxy, shell: /bin/bash, uid: 2100096}
galaxy_group: {name: ec-galaxy-group, gid: 2100210}
#---------------------------------------------------------------------
galaxy_commit_id: release_21.09
galaxy_force_checkout: true
#we installed conda ourself, do not want this
#miniconda_prefix: "{{ galaxy_tool_dependency_dir }}/_conda"
#miniconda_version: 4.7.12
#miniconda_manage_dependencies: false 

galaxy_config:
  galaxy:
#--Admin-------------------------------------------------
    brand: "FOX-portal"
    admin_users: flbernal@usit.uio.no,n.a.vazov@usit.uio.no
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    check_migrate_tools: false
    allow_user_impersonation: true
    require_login: true
    allow_user_dataset_purge: true
    expose_dataset_path: true
    password_expiration_period: 0
    session_duration: 0
    allow_user_deletion: true
    enable_quotas: true
    
# -- Authentication -------------------------------------------
    user_activation_on: true
    track_jobs_in_database: true
    smtp_server: smtp.uio.no
    ## activation_email: noreply-galaxy-hepp@galaxy-hepp.hpc.uio.no
    error_email_to: n.a.vazov@usit.uio.no
    ## instance_resource_url: http://galaxy-hepp.hpc.uio.no
    ## activation_grace_period: 0
    ## inactivity_box_content: Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address.
    ## auth_config_file: "{{ galaxy_root }}/config/auth_conf.xml"
    
#--Standard Config-------------------------------------------
    welcome_url: /static/welcome.html
    galaxy_infrastructure_url: https://galaxy01.educloud.no

#-- Cluster partition based directories -----------------------------
    #file_path: "/storage/galaxy/files"
    #new_file_path: "/tmp"
    #template_cache_path: "/storage/galaxy/compiled_templates"
    #job_working_directory: "/storage/galaxy/jobs_directory"
    #cluster_files_directory: "/storage/galaxy/slurm"

#--Jobs Configuration----------------------------------------
###    interactivetools_enable: true
###     interactivetools_map: "{{ gie_proxy_sessions_path }}"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    job_resource_params_file:  "{{ galaxy_root }}/config/job_resource_params_conf.xml"
    cleanup_job: never
    
#-- Tool Configuration----------------------------------------
    tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    tool_config_file: "{{ galaxy_root }}/config/tool_conf.xml,{{ galaxy_root }}/config/local_tool_conf.xml"
    tool_destinations_config_file: "{{ galaxy_config_dir }}/tool_destinations.yml"
    dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"    
    integrated_tool_panel_config: "integrated_tool_panel.xml"
#    tool_dependency_dir: "/storage/galaxy/dependencies"
    datatypes_config_file: "{{ galaxy_root }}/config/datatypes_conf.xml"
    
  uwsgi:
    socket: 127.0.0.1:8080
    #http: 0.0.0.0:8080
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static={{ galaxy_server_dir }}/static
      - /favicon.ico={{ galaxy_server_dir }}/static/favicon.ico
    static-safe: client/galaxy/images
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2

#-- Galaxy Config Files-----------------------------------
galaxy_config_files:
  - src: files/galaxy/config/job_conf.xml
    dest: "{{ galaxy_config.galaxy.job_config_file }}"
  - src: files/galaxy/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config.galaxy.job_resource_params_file }}"
  - src: files/galaxy/config/tool_conf.xml
    dest: "{{ galaxy_root }}/config/tool_conf.xml"
  - src: files/galaxy/config/datatypes_conf.xml
    dest: "{{ galaxy_root }}/config/datatypes_conf.xml"
  - src: files/galaxy/config/local_tool_conf.xml
    dest: "{{ galaxy_root }}/config/local_tool_conf.xml"
##   - src: files/galaxy/config/auth_conf.xml
##     dest: "{{ galaxy_root }}/config/auth_conf.xml"
    

#-- Local Tools ----------------------------------------
galaxy_local_test_tools:
  - testing_static_slurm.xml
  
#-- Local  Interactive Tools -------------------------------

## copied by the task "copy_local_*_tools.yml" in role: galaxyhepp.customized

#galaxy_local_interactive_tools:
  #- interactivetool_jupyter_notebook_fys5555.xml
  #- interactivetool_comphep.xml
  #- default_notebook.ipynb


#-- Dynamic Job Rules Files------------------------------
galaxy_dynamic_job_rules:
  - generate_slurm_job_params.py
  - destinations.py

# -- Interactive Tools Docker -------------------------
#docker_install_compose: false
#docker_users:
  #- "{{ galaxy_user.name }}"

#-- Interactive Tools configuration -------------------------
#gie_proxy_dir: /srv/gie-proxy/proxy
#gie_proxy_git_version: master
#gie_proxy_setup_nodejs: nodeenv
#gie_proxy_virtualenv_command: "{{ pip_virtualenv_command }}"
#gie_proxy_nodejs_version: "10.13.0"
#gie_proxy_virtualenv: /srv/gie-proxy/venv
#gie_proxy_setup_service: systemd
#gie_proxy_verbose: true
#gie_proxy_sessions_path: "/srv/gie-proxy/proxy/interactivetools_map.sqlite"

# systemd
galaxy_systemd_mode: mule
galaxy_zergpool_listen_addr: 127.0.0.1:8080
galaxy_restart_handler_name: "Restart Galaxy"
galaxy_systemd_zergling_env: "DRMAA_LIBRARY_PATH=/srv/drmaa/lib/libdrmaa.so.1"

