# Which mode to run galaxy's web handlers in, there are only two options: mule or zerg (zerglings + webless handlers)
galaxy_systemd_mode: "zerg"

# Mule Options
galaxy_systemd_memory_limit_mule: 32

# Zergling Options
## How many zerglings to run, >1 means you should set galaxy_zergpool=true
galaxy_systemd_zerglings: 2
galaxy_systemd_handlers: 12
galaxy_systemd_workflow_schedulers: 0

# Maximum memory limits (in GB) are set for every process in their systemd unit file, and applied through cgroups.
galaxy_systemd_memory_limit: 16
galaxy_systemd_memory_limit_reports: 5
galaxy_systemd_memory_limit_handler: 5
galaxy_systemd_memory_limit_workflow: 5
galaxy_systemd_memory_limit_zp: 8

# If we're using the zerg method, do we just want to run a single zergling or a
# pool of them? If we're running multiple, then we need the zergpool interface.
galaxy_zergpool: true
# This is where nginx should send requests (if zergpool is enabled.)
galaxy_zergpool_listen_addr: "127.0.0.1:4001"
galaxy_zergpool_socket_name: zergpool.sock
# Where the socket for the zergling will be placed
galaxy_zergpool_listen_path: "{{ galaxy_mutable_data_dir }}/{{ galaxy_zergpool_socket_name }}"

galaxy_systemd_zergling_uwsgi_config_style: "{{ galaxy_config_style | default('ini')}}"
galaxy_systemd_zergling_uwsgi_config_file: "{{ galaxy_config_file }}"

# Any extra env vars you wish to set for Zerglings OR Mules (anything that runs web)
galaxy_systemd_zergling_env: ""
# Any extra env vars to pass to the handlers
galaxy_systemd_handler_env: ""

# Do you want to deploy reports too? No, of course not.
galaxy_systemd_reports: false
galaxy_reports_path: "{{ galaxy_config_dir  }}/reports.yml"
