---
- hosts: galaxy01_educloud
  become: true
  vars:
      galaxy_diff_mode_verbose: true
      TSD_CLIENT_ID:  "{{ lookup('file', '/uio/kant/usit-ft-u1/nikolaiv/galaxy-fox-oidc-secrets/tsd_client_id') }}"
      TSD_CLIENT_SECRET:  "{{ lookup('file', '/uio/kant/usit-ft-u1/nikolaiv/galaxy-fox-oidc-secrets/tsd_client_secret') }}"
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - role: galaxyproject.galaxy
      become: true
      become_user: "{{ galaxy_user.name }}"
      # customized tasks
    - role: lifeportalfox.customized
      become: true
      become_user: "{{ galaxy_user.name }}"
    - role: slurmdrmaa.galaxy
      become: yes
      become_user: root
    - centos.nginx

  environment:
    #http_proxy: socks5://127.0.0.1:12354
    #https_proxy: socks5://127.0.0.1:12354
    https_proxy: http://localhost:8123
    http_proxy: http://localhost:8123
    
    # Enable the following variable in the terminal of the remote host (galaxy01.edicloud.no) in order to run
    # systemctl --user status galaxy and othe systemctl commands as ec-galaxy user
    #XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
    # export XDG_RUNTIME_DIR=/run/user/2100096
    ## Then as ec-galaxy user run
    ## systemctl --user status galaxy
