---
- hosts: galaxy01_educloud
  vars:
      galaxy_diff_mode_verbose: true
  become: true
  #vars:
      #passwd_file_contents: "{{ lookup('file', '/uio/kant/usit-ft-u1/nikolaiv/galaxy-hepp-ldap-pass/galaxy_hepp_ldap_pass') }}"

  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - role: galaxyproject.galaxy
      become: true
      become_user: "{{ galaxy_user.name }}"
      # customized tasks
    - role: lifeportalfox.customized
      become: true
      become_user: "{{ galaxy_user.name }}"
    - role: slurmdrmaa.galaxy
      become: yes
      become_user: root
    - centos.nginx

  environment:
    http_proxy: socks5://127.0.0.1:12354
    https_proxy: socks5://127.0.0.1:12354
    
    # Enable the following variable in the terminal of the remote host (galaxy01.edicloud.no) in order to run
    # systemctl --user status galaxy and othe systemctl commands as ec-galaxy user
    #XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
