---
- hosts: galaxy01_educloud
  vars:
      galaxy_diff_mode_verbose: true
  become: true
  #vars:
      #passwd_file_contents: "{{ lookup('file', '/uio/kant/usit-ft-u1/nikolaiv/galaxy-hepp-ldap-pass/galaxy_hepp_ldap_pass') }}"
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy.service
        daemon_reload: true
        state: restarted
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
      become: yes
      become_user: "{{ galaxy_user.name }}"

  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - role: galaxyproject.galaxy
      become: true
      become_user: "{{ galaxy_user.name }}"
      # customized tasks
    - role: lifeportalfox.customized
      become: true
      become_user: "{{ galaxy_user.name }}"
##    - centos.zpath (Copies welcome page)
#    - selinux.galaxy
      # "selinux.galaxy.uwsgi" might be optional for uwsgi
      # in case the context cannot be changed by 
      # the previous role "selinux.galaxy"
#    - selinux.galaxy.uwsgi
    - role: slurmdrmaa.galaxy
      become: yes
      become_user: root
    - role: usegalaxy_eu.galaxy_systemd
      become: true
      become_user: "{{ galaxy_user.name }}"
    - centos.nginx

  environment:
    http_proxy: socks5://127.0.0.1:12354
    https_proxy: socks5://127.0.0.1:12354
