---
- name: galaxy handler daemon reload
  systemd:
    daemon_reload: yes
    scope: user
  environment:
        XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
    
- name: galaxy workflow scheduler daemon reload
  systemd:
    daemon_reload: yes
    scope: user
  environment:
        XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"

- name: galaxy mule start
  systemd:
      name: galaxy.service
      state: started
      scope: user
  environment:
        XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
