---

- name: Pull the tool directories from Sabry tool repo
  git:
    repo: https://nikolaiv:<TOKEN>@github.uio.no/IT-ITF/sw-portals-team-lifeportal-fox-tools.git
    dest: "{{ tools_root }}" # /cluster/galaxy/data/tools/prod
    update: yes
    version: master
  when:  tools_root is defined
