- name: Deploy Galaxy Unit
  template:
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_group.name }}"
    mode: 0644
    src: galaxy.service.j2
    dest: /home/ec-galaxy/.config/systemd/user/galaxy.service
  notify:
    - galaxy handler daemon reload
    - galaxy mule start

- name: Enable Galaxy Unit and Run a user service when XDG_RUNTIME_DIR is not set on remote login
  systemd:
    name: galaxy.service
    state: started
    scope: user
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
