---

- name: Manage Paths
  block:

   - name: Deploy Galaxy Reports Unit
      template:
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_group.name }}"
        mode: 0644
        src: systemd/galaxy-reports.service.j2
        dest: /home/{{ galaxy_user.name }}/.config/systemd/user/galaxy-reports.service
      notify:
        - daemon reload

    #- name: Enable Galaxy Unit
      #systemd:
        #name: galaxy.service
        #enabled: yes

    - name: Enable a user service when XDG_RUNTIME_DIR is not set on remote login
      systemd:
          name: galaxy-reports.service
          enabled: yes
          scope: user
          state: started
      environment:
          XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"

  #remote_user: "{{ galaxy_remote_users.root | default(__galaxy_remote_user) }}"
  #become: "{{ true if galaxy_become_users.root is defined else __galaxy_become }}"
  #become_user: "{{ galaxy_become_users.root | default(__galaxy_become_user) }}"
  become_user: "{{ galaxy_user.name }}"
