---

- name: Manage Paths
  block:

    - name: Deploy Galaxy Unit
      template:
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_group.name }}"
        mode: 0644
        src: systemd/galaxy.service.j2
        dest: /home/{{ galaxy_user.name }}/.config/systemd/user/galaxy.service
      notify:
        - daemon reload
        - galaxy mule restart

    - name: Enable a user service
      systemd:
          name: galaxy.service
          enabled: yes
          scope: user

  #remote_user: "{{ galaxy_remote_users.root | default(__galaxy_remote_user) }}"
  #become: "{{ true if galaxy_become_users.root is defined else __galaxy_become }}"
  #become_user: "{{ galaxy_become_users.root | default(__galaxy_become_user) }}"
  become_user: "{{ galaxy_user.name }}"
