---

# Having pip installed on $PYTHONPATH can break upgrading it, so we install
# once with $PYTHONPATH set (in case it's needed for virtualenv) and then once
# the venv is created we upgrade pip with $PYTHONPATH unset

- name: Create Galaxy virtualenv
  pip:
    name: pip
    virtualenv: "{{ galaxy_venv_dir }}"
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ galaxy_virtualenv_python | default(omit) }}"
  environment:
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: Ensure pip and setuptools are the latest release
  pip:
    name: 
      - pip
      - setuptools
    state: latest
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    #PYTHONPATH:  null
    # In order to use system-wide installed socks we need to set the PYTHONPATH  to both venv one and the system wide one
    # The venv one is /galaxy/srv/galaxy/venv/lib/python3.6/site-packages/
    # The system one is : /usr/lib/python3.6/site-packages/
    PYTHONPATH:  "{{ galaxy_venv_dir }}/lib/python3.6/site-packages/:/usr/lib/python3.6/site-packages/"
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
