---

- name: Creates directory for local statistics tools
  file:
    path: "{{ galaxy_local_tools_dir }}/statistics"
    state: directory
    owner: galaxy
    group: galaxy
    mode: 0775
    recurse: yes

- name: Copy local statistics tool wrappers
  copy:
    src: "{{ galaxy_local_tools_src_dir }}/statistics/{{ item }}"
    dest: "{{ galaxy_local_tools_dir }}/statistics/{{ item }}"
  with_items: "{{ galaxy_local_statistics_tools | default([]) }}"
  when: galaxy_local_statistics_tools is defined
