---
# defaults file for galaxyproject.galaxy

# TODO: Magical restarters depending on how you're running Galaxy.
- name: default restart galaxy handler
  debug:
    msg: "RESTARTER NOT IMPLEMENTED - Please restart Galaxy manually. You can define your own handler and enable it with `galaxy_restart_handler_name`"

- name: email administrator with commit id
  mail:
    from: "{{ galaxy_admin_email_from | default( 'root' ) }}"
    to: "{{ galaxy_admin_email_to }}"
    subject: "Galaxy instance {{ galaxy_instance_hostname | default( inventory_hostname ) }} is at commit {{ galaxy_commit_id }}"
    body: " "
  when: galaxy_admin_email_to is defined

- name: daemon reload
  systemd:
    daemon_reload: yes
    scope: user
  environment:
          XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"

- name: galaxy mule start
  systemd:
      name: galaxy.service
      state: started
      scope: user
  environment:
          XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"

- name: galaxy mule restart
  systemd:
      name: galaxy.service
      state: restarted
      scope: user
  environment:
          XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"
